//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrenairTraining.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class containertype
    {
        public containertype()
        {
            this.container = new HashSet<container>();
        }
    
        public int containertype_id { get; set; }
        public string containertype_name { get; set; }
    
        public virtual ICollection<container> container { get; set; }
    }
}
