//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrenairTraining.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class department
    {
        public department()
        {
            this.containertodepartment = new HashSet<containertodepartment>();
            this.user = new HashSet<user>();
        }
    
        public int department_id { get; set; }
        public string department_name { get; set; }
        public Nullable<bool> deleted { get; set; }
    
        public virtual ICollection<containertodepartment> containertodepartment { get; set; }
        public virtual ICollection<user> user { get; set; }
    }
}
