//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrenairTraining.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class log
    {
        public int note_id { get; set; }
        public System.DateTime datetime { get; set; }
        public string operation_code { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> objectcode_id { get; set; }
        public Nullable<int> object_id { get; set; }
        public string ip { get; set; }
    
        public virtual objectcode objectcode { get; set; }
        public virtual user user { get; set; }
    }
}
