//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrenairTraining.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class material
    {
        public int material_id { get; set; }
        public string material_name { get; set; }
        public int container_id { get; set; }
        public Nullable<bool> deleted { get; set; }
        public byte[] material_content { get; set; }
        public string file_name { get; set; }
        public Nullable<double> file_size { get; set; }
    }
}
