//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrenairTraining.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class objectcode
    {
        public objectcode()
        {
            this.log = new HashSet<log>();
        }
    
        public int objectcode_id { get; set; }
        public string objectcode_name { get; set; }
    
        public virtual ICollection<log> log { get; set; }
    }
}
