//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrenairTraining.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class questiontype
    {
        public questiontype()
        {
            this.question = new HashSet<question>();
        }
    
        public int questiontype_id { get; set; }
        public string questiontype_name { get; set; }
        public bool deleted { get; set; }
    
        public virtual ICollection<question> question { get; set; }
    }
}
