//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrenairTraining.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class testconfig
    {
        public int testconf_id { get; set; }
        public string testconf_name { get; set; }
        public Nullable<System.TimeSpan> time { get; set; }
        public Nullable<bool> deleted { get; set; }
        public string themes { get; set; }
        public string questions { get; set; }
        public Nullable<int> department_id { get; set; }
    }
}
