//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrenairTraining.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class testtouser
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public int testconf_id { get; set; }
        public Nullable<bool> is_completed { get; set; }
        public Nullable<System.DateTime> date_of_assignment { get; set; }
        public Nullable<bool> deleted { get; set; }
    
        public virtual testconfig testconfig { get; set; }
        public virtual user user { get; set; }
    }
}
