//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrenairTraining.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.log = new HashSet<log>();
            this.session = new HashSet<session>();
            this.testtouser = new HashSet<testtouser>();
        }
    
        public int user_id { get; set; }
        public string user_name { get; set; }
        public Nullable<int> tab_num { get; set; }
        public string password { get; set; }
        public string firstname { get; set; }
        public string surname { get; set; }
        public string patronymic { get; set; }
        public string fio { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
        public Nullable<int> department_id { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
        public Nullable<bool> loggedon { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<System.DateTime> last_activity_date { get; set; }
        public int role_id { get; set; }
    
        public virtual department department { get; set; }
        public virtual ICollection<log> log { get; set; }
        public virtual role role { get; set; }
        public virtual ICollection<session> session { get; set; }
        public virtual ICollection<testtouser> testtouser { get; set; }
    }
}
